import type { Metadata } from "next";
import "react-toastify/dist/ReactToastify.css";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ToastContainer } from "react-toastify";
import ErrorBoundary from "@/components/ErrorBoundary";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "IT-LEARN",
  description: "Generated by create next app",
  icons: {
    icon: "/logo2.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <ErrorBoundary>
        <html lang="en" className="overflow-x-hidden">
          <body className={inter.className}>
            <ToastContainer />
            {children}
          </body>
        </html>
      </ErrorBoundary>
    </ClerkProvider>
  );
}
